name: Build and Deploy Docker Image

on:
  push:
    branches:
      - main  # Deploys when code is pushed to the main branch
    tags:
      - 'v*'  # Optional: Deploys on version tags, e.g., v1.0, v1.1, etc.

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Check out the repository
        uses: actions/checkout@v4

      - name: Set up Docker Build
        uses: docker/setup-buildx-action@v2

      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and Push Docker Image
        uses: docker/build-push-action@v4
        with:
          context: ./backend/video_processor/go
          file: ./backend/video_processor/go/Dockerfile
          push: true
          tags: |
            ghcr.io/anhqv-video-processor:latest
            ghcr.io/anhqv-video-processor:${{ github.sha }}

      - name: Log out of GitHub Container Registry
        if: always()
        run: docker logout ghcr.io
