# This workflow will build a golang project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-go

name: Go

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: '1.23.1'

      - name: Install Dependencies
        run: |
          sudo apt update
          sudo apt install ffmpeg -y
          
      - name: Build
        run: |
          cd ./go/
          go build -v ./...

      - name: Test with coverage
        run: |
          cd ./go/
          go test -v -coverprofile=coverage.out -covermode=atomic ./...

      - name: Upload coverage report
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: coverage-report
          path: coverage.out

      - name: Generate HTML coverage report
        run: |
          cd ./go/
          go tool cover -html=coverage.out -o coverage.html

      - name: Upload HTML coverage report
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: html-coverage-report
          path: coverage.html
